export const courts = [
  {
    index: 1,
    name: "노란공테니스",
    location: "경기도 고양시 일산동구 성현로 \n 268번길 267-18",
    call: "010-5252-3366",
    homepage: "https://blog.naver.com/p139154",
    court: "실내 레슨/연습장, 실외1면",
    etc: "",
  },
  {
    index: 2,
    name: "ES 실내 테니스장",
    location: "충북 청주시 청원구 내수읍  \n 내수로 303",
    call: "010-6681-8857",
    homepage: "",
    court: "인조잔디 실내 1면, 실외 1면 ",
    etc: "남,여 샤워실 \n 옥상 볼머신 연습 하드코트",
  },
  {
    index: 3,
    name: "숲속 실내테니스",
    location: "경기도 여주시 가남읍  \n  상활2길 70-30",
    call: "010-2726-7814",
    homepage: "",
    court: "실내 2면 인조잔디",
    etc: "실외 3면 인조잔디",
  },
];

export const academies = [
  {
    index: 1,
    name: "노란공테니스",
    location: "경기도 고양시 일산동구 성현로 \n 268번길 267-18",
    call: "010-5252-3366",
    homepage: "https://blog.naver.com/p139154",
    court: "실내 레슨/연습장, 실외1면",
    etc: "",
  },
  {
    index: 2,
    name: "VTG테니스장",
    location: "서울특별시 영등포구 여의나루로 42 \n 여의도종합상가 4층",
    call: "010-6367-4405",
    homepage: "https://vtgtennis.modoo.at",
    court: "하드코트 미니코트 3면",
    etc: "",
  },
  {
    index: 3,
    name: "송지호실내테니스아카데미",
    location: "경기도 부천시 부천로103 3층",
    call: "032-218-0707",
    homepage: "https://songtennis.modoo.at",
    court: "볼머신, 옥상연습장",
    etc: "",
  },
  {
    index: 4,
    name: "송지호실내테니스아카데미",
    location: "인천시 계양구 계산동 18-17",
    call: "032-555-4644",
    homepage: "https://songtennis.modoo.at",
    court: "실내 연습장",
    etc: "",
  },
  {
    index: 5,
    name: "송지호실내테니스아카데미",
    location: "경기도 시흥시 서해안로 1579",
    call: "031-312-0779",
    homepage: "https://songtennis.modoo.at",
    court: "볼머신",
    etc: "",
  },
  {
    index: 6,
    name: "이주용 테니스 클리닉",
    location:
      "경기도 성남시 분당구 미금로 184\n 까치마을 1단지 105동 앞 테니스장",
    call: "010-3306-7271",
    homepage: "https://band.us/@tennisclinic",
    court: "실외 정식규격코트 1면/ \n 보조코트(가로폭 정식코트의 3/5 크기)1면",
    etc: "클레이코트",
  },
  {
    index: 7,
    name: "펀펀테니스",
    location: "인천 서구 두밀로136 \n (경기도 김포 장기동 근처)",
    call: "070-8843-7655",
    homepage: "https://www.funfuntennis.co.kr",
    court: "실내 레슨코트1면/연습코트1면\n(정식규격에서 좌우위아래 50센치작음)",
    etc: "인조잔디코트/볼머신/스크린테니스/샤워실",
  },
  {
    index: 8,
    name: "손오공 테니스 아카데미",
    location: "서울 영등포구 가마산로 540 \n 바다마을 상가",
    call: "02-845-2800",
    homepage: "http://cafe.naver.com/sonogongtennis",
    court: "하드코트,볼머신,샤워장,라커",
    etc: "테니스 용품및 거트수리 샾",
  },
  {
    index: 9,
    name: "JTA 통 테니스",
    location: "청주시 상당구 산성로  \n 92번길 13 5층",
    call: "010-9666-5258",
    homepage: "blog.naver.com/tennistong",
    court: "실내 2/3크기 레슨코트 2면, 하드코트",
    etc: "볼머신연습",
  },
];

export const shops = [
  {
    index: 1,
    name: "스매싱 스포츠",
    ceo: "이철희",
    location: "경기도 군포시 고산로 166 \n SK 벤티움",
    call: "031-427-1787",
    homepage2: "",
    homepage3: "",
    homepage: "http://www.smashingsports.co.kr",
    category: "테니스 포함 모든 스포츠 용품",
  },
  {
    index: 2,
    name: "주주 스포츠",
    ceo: "박길택",
    location: "부산 기장군 기장읍 청강로 \n 85번길 115",
    call: "051-724-5009",
    homepage2: "",
    homepage3: "",
    homepage: "http://www.jujusports.co.kr",
    category: "테니스 포함 모든 스포츠 용품",
  },
  {
    index: 3,
    name: "썬 스포츠",
    ceo: "김영식",
    location: "서울시 중구 을지로 248 \n (을지로6가, 국립중앙의료원 건너편)",
    call: "매장 : 02-2268-3663 \n 담당자 : 010-7566-8081",

    homepage2: "",
    homepage3: "",
    homepage: "https://band.us/n/aba743ee0dHas",
    category: "테니스&배드민턴&탁구&스쿼시 \n 아디다스 스페셜 스토어",
  },
  {
    index: 4,
    name: "슈클 테니스화",
    ceo: "김남용",
    location: "경기도 용인시 처인구  \n 모현읍 포은대로 896",
    call: "010-5333-6024",
    homepage: "www.sucl.co.kr",
    homepage2: "",
    homepage3: "",
    category: "대한민국 대표 테니스화",
  },
  {
    index: 6,
    name: "스포츠 코리아[구,거성 테니스]",
    ceo: "",
    location: "경기도 성남시 분당구 \n 수내3동 불정로 255",
    call: "031-711-0342",
    homepage: "홈페이지 : https://spotel.com",
    homepage2: "카카오채널 소식 : https://pf.kakao.com/_xcBBad/chat",
    homepage3: "네이버 톡톡 : https://talk.naver.com/ct/wc4v44",
    category: "",
  },
];

export const clubs = [
  {
    index: 1,
    name: "노란공 레슨자 클럽",
    court: "노란공테니스장",
    location: "경기도 고양시 일산동구 성현로 \n 268번길 267-18",
    call: "010-5252-3366",
    homepage: "https://blog.naver.com/p139154",
    when: "1년 365일 하루종일",
    who: "노란공테니스 레슨자",
    dues: "입회비 없음 / 월회비 없음",
  },
  {
    index: 2,
    name: "한강 테니스클럽",
    court: "이촌한강공원 테니스장",
    location: "서울 용산구 용산동6가 450-1",
    call: "010-3710-4972",
    homepage: "",
    when: "매일 오전 6시~12시",
    who: "남녀 게임가능한 초,중,상급자",
    dues: "입회비 20만원 / 월 4만원",
  },
  {
    index: 3,
    name: "기흥 골드클럽",
    court: "용인 골드 테니스장",
    location: "경기 용인시 기흥구 고매동 33-12",
    call: "010-9074-8430",
    homepage: "",
    when: "매일 오전 9시 ~ 오후 9시",
    who: "남성:30~50대 은배부이상 \n 여성:전국대회 출전 및 입상자",
    dues: "입회비 20만원 / 월 2만원",
  },
  {
    index: 4,
    name: "포인트 클럽",
    court: "부천 복사골 테니스장",
    location: "경기 부천시 장말로293번길 45",
    call: "010-7332-3598",
    homepage: "",
    when: "화,목 저녁 6시~10시 \n 토,일 오전 10시~14시",
    who: "테니스 열정 가득한 테니스인",
    dues: "입회비 10만원 / 월 5만원",
  },
  {
    index: 5,
    name: "둥지 테니스클럽",
    court: "오륜테니스장",
    location: "서울시 송파구 동남로 417 ",
    call: "010-9088-2061",
    homepage: "https://band.us/band/79532129",
    when: "월~금 오전 07시~10시",
    who: "남,여 게임 가능하신분 ",
    dues: "입회비 10만원 / 월 4만원",
  },
  {
    index: 6,
    name: "동조 클럽",
    court: "불로 시민체육공원 테니스장",
    location: "대구시 동구 불로동 668-2",
    call: "010-2222-7491",
    homepage: "",
    when: "매일 오전 6시30분 ~ 9시30분 \n (첫째주 일요일 월례대회)",
    who: "누구나 가입환영",
    dues: "입회비 10만원 / 월 4만원",
  },
  {
    index: 7,
    name: "나주 클럽",
    court: "남산공원 테니스장",
    location: "전라남도 나주시 남산길 23",
    call: "010-3728-2599",
    homepage: "",
    when: "365일 언제나 운동 - 하드코트",
    who: "테니스 사랑하는 누구나 환영",
    dues: "입회비 5만원 / 남자 월 35,000원 \n 여자,65세이상 월 2만원",
  },
  {
    index: 8,
    name: "365ET 밴드 모임",
    court: "부천 해그늘 체육공원 6번코트",
    location: "경기도 부천시 상동 도약삼거리",
    call: "010-7337-8425",
    homepage: "https://band.us/band/78835140",
    when: "365일 매일 4시간",
    who: "게임 가능하시분 누구나",
    dues: "입회비 없음 / 월 1만원",
  },
  {
    index: 9,
    name: "함지TC",
    court: "구암 테니스장",
    location: "대구 광역시 북구 구암동 70-4  ",
    call: "010-7337-8425",
    homepage: "",
    when: "주중 14시~17시 \n 주말 13시~16시 \n 인조잔디 2면 사용",
    who: "테니스 열정있으신분 누구나 가능",
    dues: "입회비 5만원 / 월 1만원",
  },
  {
    index: 10,
    name: "향촌테니스 클럽",
    court: "대전 서구 향촌아파트 테니스장",
    location: "대전 서구 둔산동 970",
    call: "",
    homepage: "",
    when: "365일 저녁 9시까지 언제나 \n 클레이코트 2면",
    who: "",
    dues: "입회비 10만원 \n 월 남성(2.5만) 여성(2만)",
  },
];
